### ISSUE TITLE
Prototype Pollution Security Vulnerability

### ISSUE THREAD

**Issue by smonusbonus** [micro-tools/log4bro#16]
Can we fix this by updating @google-cloud/logging? Shall I create a PR?

![Screenshot 2019-07-31 at 09 01 07](https://user-images.githubusercontent.com/1876194/62190534-da7fdd80-b371-11e9-8c84-98cc94c63d17.png)

https://www.npmjs.com/advisories/1066

**Comment by krystianity** [comment]
Hi @smonusbonus will upgrade today, thanks.

**Comment by smonusbonus** [comment]
I think it was a false positive, after removing the package-lock and reinstalling the packages the warning did not show up again.
